INSERT INTO burgers (burger_name, devoured) VALUES ("Beef Burger", true);
INSERT INTO burgers (burger_name, devoured) VALUES ("Triple-Stacked Avocado Burger", true);
INSERT INTO burgers (burger_name, devoured) VALUES ("Chicken Cheeseburger", ture);
INSERT INTO burgers (burger_name, devoured) VALUES ("Veggie Burger", true);
INSERT INTO burgers (burger_name, devoured) VALUES ("Portobello Mushroom Burger", true);
INSERT INTO burgers (burger_name, devoured) VALUES ("Black Bean Burgers", true);
INSERT INTO burgers (burger_name, devoured) VALUES ("Elk Burgers", true);
INSERT INTO burgers (burger_name, devoured) VALUES ("Turkey Burger", true);
INSERT INTO burgers (burger_name, devoured) VALUES ("Vegan Burger", true);
INSERT INTO burgers (burger_name, devoured) VALUES ("Bison Burger", true);
INSERT INTO burgers (burger_name, devoured) VALUES ("Wild Salmon Burger", true);
